### ISSUE TITLE
Game won't start.

### ISSUE THREAD

**Issue by RychuP** [Melonator/Tower-of-Doom#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Game won't start and the error shows:
The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.

### Expected Behavior

Game starts in debug mode.

### Steps To Reproduce

1. Clone from github.
2. Press RUN in debug mode.

**Comment by sitiom** [comment]
Assuming you are running this in VS 2019, update to VS 2022 (has the .NET 6 SDK).

**Comment by RychuP** [comment]
Thanks. I am updating to 2022 now. I will try again soon.

**Comment by RychuP** [comment]
It works. Cool game.
